spring:
  datasource:
    url: jdbc:mysql://47.104.199.14:3310/fo-up?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 950620
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
#        hbm2ddl:
#          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet: 
    multipart:
      # Enable multipart uploads
      enabled: true
      # xThreshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB

server:
  port: 8089
  servlet:
    context-path: /up

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
up:
  file:
    upload-dir: ./uploads
